#!/bin/bash
# po/update-pot.sh
#
# Regenerates po/pkgbuild_manager.pot by extracting translatable strings
# from ALL project sources automatically, syncs LINGUAS <-> .po files,
# and runs msgmerge on every existing .po file at the end.
#
# ──────────────────────────────────────────────────────────────────────────────
# HOW IT WORKS
# ──────────────────────────────────────────────────────────────────────────────
#
#  Step 1 — Rust source scan
#    Finds every src/**/*.rs file that contains gettext() calls and runs
#    xgettext -L C on them to produce a temporary rust.pot.
#    Files without gettext() are skipped to avoid parser noise.
#
#  Step 2 — Python source scan
#    Finds every src/**/*.py and data/**/*.py file and runs
#    xgettext -L Python (keyword: _()) to produce a temporary python.pot.
#
#  Step 3 — Blueprint source scan
#    Finds every data/ui/*.blp file and extracts strings marked with _().
#
#  Step 4 — Bash extraction + POTFILES.in regeneration
#    Extracts the English msgid (argument 1) directly from _i18n.
#    Rewrites po/POTFILES.in from the discovered file list.
#    Do not edit this file manually — it is always overwritten.
#
#  Step 5 — .pot merge
#    Combines rust.pot + python.pot + blueprint.pot + bash.pot via
#    msgcat --use-first.
#
#  Step 6 — Header fixup
#    Writes the final po/pkgbuild_manager.pot with the correct
#    Project-Id-Version (read from Cargo.toml) and POT-Creation-Date.
#
#  Step 7 — Bidirectional LINGUAS <-> .po sync
#    • A .po file found in po/ without a matching LINGUAS entry
#      → entry is added to LINGUAS automatically.
#    • A language listed in LINGUAS without a corresponding .po file
#      → file is created via msginit automatically.
#    All .po files are then updated with msgmerge --update so new strings
#    are merged and obsolete strings are flagged.
#
# ──────────────────────────────────────────────────────────────────────────────
# LOCALE DETECTION (runtime, not this script)
# ──────────────────────────────────────────────────────────────────────────────
#
#  At application runtime the locale is resolved in this order:
#    $LANGUAGE  →  $LC_ALL  →  $LC_MESSAGES  →  $LANG
#  Falls back to English if no matching translation is found.
#
# ──────────────────────────────────────────────────────────────────────────────
# USAGE
# ──────────────────────────────────────────────────────────────────────────────
#
#   cd <repo root>
#   bash po/update-pot.sh
#
#  Safe to run repeatedly — existing translations are never overwritten,
#  only merged. New strings get empty msgstr entries to be filled in.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
PO_DIR="$ROOT/po"
OUT="$PO_DIR/pkgbuild_manager.pot"
POTFILES="$PO_DIR/POTFILES.in"
LINGUAS_FILE="$PO_DIR/LINGUAS"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "=== PKGBUILD Manager — regenerating .pot ==="
echo ""

# ── 1. Discover and filter Rust files containing gettext() ───────────────────
echo "[1/7] Discovering Rust files (.rs with gettext())..."
# Filter only .rs files that actually contain gettext() — avoids xgettext
# warnings when parsing Rust syntax as C (arrows, lifetimes, etc.)
mapfile -t RUST_FILES < <(
    find "$ROOT/src" -name "*.rs" -type f \
    | xargs grep -l 'gettext(' 2>/dev/null \
    | sort
)
echo "   → ${#RUST_FILES[@]} .rs files with gettext() found"

if [[ ${#RUST_FILES[@]} -gt 0 ]]; then
    # 2>/dev/null suppresses false warnings from Rust syntax (arrows ->, lifetimes 'a, etc.)
    xgettext \
        --from-code=UTF-8 \
        --language=C \
        --keyword=gettext \
        --add-comments=translators \
        --package-name=pkgbuild_manager \
        --package-version="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*= *"//;s/"//')" \
        --output="$TMP/rust.pot" \
        "${RUST_FILES[@]}" 2>/dev/null
    COUNT=$(grep -c '^msgid ' "$TMP/rust.pot" 2>/dev/null || echo 0)
    echo "   → rust.pot generated ($COUNT entries)"
else
    echo "   → no .rs files with gettext() found"
fi

# ── 2. Discover Python files ──────────────────────────────────────────────────
echo "[2/7] Discovering Python files (.py with _())..."
mapfile -t PY_FILES < <(
    {
        find "$ROOT/src"  -name "*.py" -type f
        find "$ROOT/data" -name "*.py" -type f
    } | sort -u
)
echo "   → ${#PY_FILES[@]} .py files found"

if [[ ${#PY_FILES[@]} -gt 0 ]]; then
    xgettext \
        --from-code=UTF-8 \
        --language=Python \
        --keyword=_ \
        --add-comments=translators \
        --package-name=pkgbuild_manager \
        --output="$TMP/python.pot" \
        "${PY_FILES[@]}" 2>/dev/null || true
    if [[ -f "$TMP/python.pot" ]]; then
        COUNT=$(grep -c '^msgid ' "$TMP/python.pot" 2>/dev/null || echo 0)
        echo "   → python.pot generated ($COUNT entries)"
    else
        echo "   → python.pot empty (no _() strings found in .py files)"
    fi
else
    echo "   → no .py files found"
fi

# ── 3. Discover Blueprint files and extract _() strings ──────────────────────
echo "[3/7] Discovering Blueprint files (.blp)..."
mapfile -t BLUEPRINT_FILES < <(
    find "$ROOT/data/ui" -name "*.blp" -type f | sort
)
echo "   → ${#BLUEPRINT_FILES[@]} .blp files found"

if [[ ${#BLUEPRINT_FILES[@]} -gt 0 ]]; then
    # Blueprint's translated-string syntax is _("...") and is compatible
    # with xgettext's C string scanner.
    xgettext \
        --from-code=UTF-8 \
        --language=C \
        --keyword=_ \
        --add-comments=Translators \
        --package-name=pkgbuild_manager \
        --output="$TMP/blueprint.pot" \
        "${BLUEPRINT_FILES[@]}" 2>/dev/null
    COUNT=$(grep -c '^msgid ' "$TMP/blueprint.pot" 2>/dev/null || echo 0)
    echo "   → blueprint.pot generated ($COUNT entries)"
fi

# ── 4. Extract Bash _getmsg() strings and update POTFILES.in ─────────────────
echo "[4/7] Extracting Bash _getmsg() strings and updating POTFILES.in..."
BASH_I18N="$ROOT/data/nautilus-scripts/_i18n"
xgettext \
    --from-code=UTF-8 \
    --language=Shell \
    --keyword=_getmsg:1 \
    --add-comments=translators \
    --package-name=pkgbuild_manager \
    --output="$TMP/bash.pot" \
    "$BASH_I18N"
{
    echo "# Auto-generated by po/update-pot.sh — do not edit manually"
    echo ""
    for f in "${RUST_FILES[@]}" "${PY_FILES[@]}" "${BLUEPRINT_FILES[@]}"; do
        echo "${f#"$ROOT/"}"
    done
    echo "${BASH_I18N#"$ROOT/"}"
} > "$POTFILES"
echo "   → bash.pot generated ($(grep -c '^msgid ' "$TMP/bash.pot") entries)"
echo "   → POTFILES.in updated with $((${#RUST_FILES[@]} + ${#PY_FILES[@]} + ${#BLUEPRINT_FILES[@]} + 1)) entries"

# ── 5. Merge all sources ──────────────────────────────────────────────────────
echo "[5/7] Merging extracted Rust, Python, Blueprint and Bash .pot files..."
MERGE=()
[[ -f "$TMP/rust.pot" ]]   && MERGE+=("$TMP/rust.pot")
[[ -f "$TMP/python.pot" ]] && MERGE+=("$TMP/python.pot")
[[ -f "$TMP/blueprint.pot" ]] && MERGE+=("$TMP/blueprint.pot")
[[ -f "$TMP/bash.pot" ]]   && MERGE+=("$TMP/bash.pot")

msgcat \
    --use-first \
    --output="$TMP/merged.pot" \
    "${MERGE[@]}"

TOTAL=$(grep -c '^msgid ' "$TMP/merged.pot" 2>/dev/null || echo 0)
echo "   → $TOTAL entries merged in total"

# ── 6. Fix header and write final .pot ────────────────────────────────────────
echo "[6/7] Writing $OUT..."
PKG_VER=$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*= *"//;s/"//')
DATE=$(date +"%Y-%m-%d %H:%M%z")

sed \
    -e "s|^\"Project-Id-Version:.*|\"Project-Id-Version: pkgbuild_manager $PKG_VER\\\\n\"|" \
    -e "s|^\"POT-Creation-Date:.*|\"POT-Creation-Date: $DATE\\\\n\"|" \
    -e "s|^\"PO-Revision-Date:.*|\"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\\\n\"|" \
    -e "s|^\"Last-Translator:.*|\"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\\\n\"|" \
    -e "s|^\"Language-Team:.*|\"Language-Team: LANGUAGE <LL@li.org>\\\\n\"|" \
    -e "s|^\"Language:.*|\"Language: \\\\n\"|" \
    "$TMP/merged.pot" > "$OUT"

echo "   → $OUT written"

# ── 7. Sync LINGUAS <-> .po files ────────────────────────────────────────────
echo "[7/7] Syncing LINGUAS <-> .po files..."

declare -A LINGUAS_SET
while IFS= read -r lang || [[ -n "$lang" ]]; do
    lang="$(echo "$lang" | tr -d '[:space:]')"
    [[ -z "$lang" || "$lang" == \#* ]] && continue
    LINGUAS_SET["$lang"]=1
done < "$LINGUAS_FILE"

ADDED_TO_LINGUAS=()
CREATED_PO=()

# 6a. .po exists but is not in LINGUAS → add it
for po_file in "$PO_DIR"/*.po; do
    [[ -f "$po_file" ]] || continue
    lang=$(basename "$po_file" .po)
    if [[ -z "${LINGUAS_SET[$lang]:-}" ]]; then
        echo "   + LINGUAS: adding '$lang' (.po file exists)"
        echo "$lang" >> "$LINGUAS_FILE"
        LINGUAS_SET["$lang"]=1
        ADDED_TO_LINGUAS+=("$lang")
    fi
done

# 6b. Language in LINGUAS without a .po file → create via msginit
for lang in "${!LINGUAS_SET[@]}"; do
    po_file="$PO_DIR/$lang.po"
    if [[ ! -f "$po_file" ]]; then
        echo "   + Creating $lang.po via msginit..."
        msginit \
            --input="$OUT" \
            --locale="$lang" \
            --output="$po_file" \
            --no-translator \
            2>/dev/null || true
        if [[ -f "$po_file" ]]; then
            COUNT=$(grep -c '^msgid ' "$po_file" 2>/dev/null || echo 0)
            echo "   → $lang.po created ($COUNT entries)"
            CREATED_PO+=("$lang")
        else
            echo "   ⚠ msginit failed for '$lang' — is the locale installed?"
        fi
    fi
done

# Rewrite LINGUAS sorted and deduplicated
sort -u "$LINGUAS_FILE" > "$TMP/linguas_sorted"
mv "$TMP/linguas_sorted" "$LINGUAS_FILE"

[[ ${#ADDED_TO_LINGUAS[@]} -gt 0 ]] && echo "   → Added to LINGUAS: ${ADDED_TO_LINGUAS[*]}"
[[ ${#CREATED_PO[@]}       -gt 0 ]] && echo "   → .po files created: ${CREATED_PO[*]}"
[[ ${#ADDED_TO_LINGUAS[@]} -eq 0 && ${#CREATED_PO[@]} -eq 0 ]] && \
    echo "   → LINGUAS and .po files are already in sync"

echo ""
echo "✓ Generated: $OUT"
echo "✓ Total entries: $TOTAL"
echo "✓ Version: pkgbuild_manager $PKG_VER"
echo "✓ Languages: $(tr '\n' ' ' < "$LINGUAS_FILE" | xargs)"

# ── Update ALL .po files automatically (always) ──────────────────────────────
echo ""
echo "=== Updating all .po files with msgmerge ==="
for po in "$PO_DIR"/*.po; do
    lang=$(basename "$po" .po)
    printf "  → %-14s" "$lang.po"
    msgmerge --quiet --update --backup=none "$po" "$OUT"
    UNTRANSLATED=$(grep -c '^msgstr ""' "$po" 2>/dev/null || echo 0)
    TOTAL_ENTRIES=$(grep -c '^msgid '   "$po" 2>/dev/null || echo 0)
    echo " ($UNTRANSLATED/$TOTAL_ENTRIES untranslated)"
done
echo "✓ All .po files updated!"
