#!/bin/bash
# PKGBUILD Manager - Full Workflow
TARGET="${1:-.}"
source "$(dirname "$0")/_i18n"
notify-send "PKGBUILD Manager" "$MSG_FULL_WORKFLOW"

LOG_PATH="${TARGET}/makepkg-full.log"

if pkgbuild_manager full-workflow "$TARGET" > "$LOG_PATH" 2>&1; then
    rm -f "$LOG_PATH"
    notify-send "PKGBUILD Manager" "$MSG_FULL_WORKFLOW_OK"
else
    notify-send -u critical "PKGBUILD Manager" "${MSG_FULL_WORKFLOW_FAIL}$(basename "$LOG_PATH")"
fi
