#!/bin/bash
# PKGBUILD Manager - Build
TARGET="$(dirname "$(realpath "${1:-.}")")" 
source "$(dirname "$0")/_i18n"
source "$(dirname "$0")/_run_in_terminal"

run_in_terminal "pkgbuild_manager build '$TARGET'"
