#!/bin/bash
# PKGBUILD Manager - Install
TARGET="$(dirname "$(realpath "${1:-.}")")" 
source "$(dirname "$0")/_i18n"
source "$(dirname "$0")/_run_in_terminal"

run_in_terminal "pkgbuild_manager install '$TARGET'"
