#!/bin/bash
# PKGBUILD Manager - Update checksums
TARGET="${1:-.}"
source "$(dirname "$0")/_i18n"
notify-send "PKGBUILD Manager" "$MSG_CHECKSUMS"

LOG_PATH="${TARGET}/checksums.log"

if pkgbuild_manager update-checksums "$TARGET" > "$LOG_PATH" 2>&1; then
    rm -f "$LOG_PATH"
    notify-send "PKGBUILD Manager" "$MSG_CHECKSUMS_OK"
else
    notify-send -u critical "PKGBUILD Manager" "${MSG_CHECKSUMS_FAIL}$(basename "$LOG_PATH")"
fi
