#!/bin/bash
# PKGBUILD Manager - Clean srcdir
TARGET="$(dirname "$(realpath "${1:-.}")")" 
source "$(dirname "$0")/_i18n"
notify-send "PKGBUILD Manager" "$MSG_CLEAN_SRC"

LOG_PATH="${TARGET}/clean_src.log"

if pkgbuild_manager clean "$TARGET" > "$LOG_PATH" 2>&1; then
    rm -f "$LOG_PATH"
    notify-send "PKGBUILD Manager" "$MSG_CLEAN_SRC_OK"
else
    notify-send -u critical "PKGBUILD Manager" "${MSG_CLEAN_SRC_FAIL}$(basename "$LOG_PATH")"
fi
