#!/bin/bash
# PKGBUILD Manager - Build NoCheck
TARGET="$(dirname "$(realpath "${1:-.}")")" 
source "$(dirname "$0")/_i18n"
notify-send "PKGBUILD Manager" "$MSG_BUILD_NOCHECK"

LOG_PATH="${TARGET}/build-nocheck.log"

if pkgbuild_manager build-nocheck "$TARGET" > "$LOG_PATH" 2>&1; then
    rm -f "$LOG_PATH"
    notify-send "PKGBUILD Manager" "$MSG_BUILD_NOCHECK_OK"
else
    notify-send -u critical "PKGBUILD Manager" "${MSG_BUILD_NOCHECK_FAIL}$(basename "$LOG_PATH")"
fi
